/// All column family names used by Vela.
/// Adding a new CF here automatically creates it on DB open.
pub const COLUMN_FAMILIES: &[&str] = &[
    "meta",
    "nid_map",
    "nid_reverse",
    "events",
    "event_ids",
    "event_id_reverse",
    "event_depth",
    "event_edges",
    "event_auth_edges",
    "event_state",
    "state_snapshots",
    "room_timeline",
    "room_state",
    "room_meta",
    "room_extremities",
    "room_bump",
    "memberships",
    "user_rooms",
    "users",
    "tokens",
    "refresh_tokens",
    "devices",
    "sync_tokens",
    "transactions",
    "account_data",
    "account_data_pos",
    "room_account_data",
    "device_keys",
    "one_time_keys",
    "cross_signing_keys",
    "to_device_messages",
    "key_backup",
    "device_key_changes",
    "media_metadata",
    "receipts",
    "room_aliases",
    "server_keys",
    "sliding_sync_conns",
    "soft_failed_events",
    // Tracks event_ids of inbound federation events we rejected.
    // Used to cascade rejection: any event whose auth_events
    // reference one of these is itself rejected. Stores the
    // rejection reason as the value (debugging aid).
    "rejected_events",
    "event_redactions",
    "user_membership_pos",
    "event_relations",
    "user_filters",
    "user_pushers",
    "user_presence",
    "federation_outbox",
    "federation_edu_cursor",
    "receipts_stream",
    "presence_stream",
    "to_device_outbound",
    "to_device_seen_message_ids",
    "device_list_outbound",
    // Per-(destination, position) buffer of m.signing_key_update EDU
    // payloads. Drained by `SigningKeyUpdateStream` and shipped via
    // the federation sender. Same value/key shape as
    // `device_list_outbound`.
    "signing_key_update_outbound",
    "room_directory",
];
