[package]
name = "vela-admin"
version.workspace = true
edition = "2024"
license.workspace = true
publish = false

[[bin]]
name = "vela-admin"
path = "src/main.rs"

[dependencies]
clap = { workspace = true, features = ["derive", "env"] }
anyhow = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
vela-store = { path = "../../vela-store" }
